export enum MarketType {
  SHARES = 'SHARES',
  COMMODITIES = 'COMMODITIES',
  CRYPTOCURRENCIES = 'CRYPTOCURRENCIES',
  CURRENCIES = 'CURRENCIES'
}

export enum MarketStatus {
  TRADEABLE = 'TRADEABLE',
  CLOSED = 'CLOSED'
}

export enum MarketModes {
  LONG_ONLY = 'LONG_ONLY',
  REGULAR = 'REGULAR',
  VIEW_ONLY = 'VIEW_ONLY',
  CLOSE_ONLY = 'CLOSE_ONLY',

}
